# Generated by Django 4.0.2 on 2022-02-09 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="InterestGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="")),
                (
                    "groupAdmin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(blank=True, to="groupApp.Interest"),
                ),
                (
                    "matches",
                    models.ManyToManyField(blank=True, to="groupApp.GroupMatch"),
                ),
                (
                    "members",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "sentLikes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="SentLikes",
                        to="groupApp.InterestGroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupmatch",
            name="group1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group1",
                to="groupApp.interestgroup",
            ),
        ),
        migrations.AddField(
            model_name="groupmatch",
            name="group2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group2",
                to="groupApp.interestgroup",
            ),
        ),
    ]
