# Generated by Django 4.0.2 on 2022-03-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupUpAccept', models.BooleanField(default=False)),
                ('isSuperGroupup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', max_length=500)),
                ('location', models.CharField(default='', max_length=255)),
                ('quote', models.TextField(default='', max_length=500)),
                ('meetingDate', models.DateField(blank=True, null=True, verbose_name='MeetingDate')),
                ('groupAdmin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('groupups', models.ManyToManyField(blank=True, to='groupApp.GroupUp')),
                ('interests', models.ManyToManyField(blank=True, to='groupApp.Interest')),
                ('members', models.ManyToManyField(blank=True, related_name='my_groups', to=settings.AUTH_USER_MODEL)),
                ('sentLikes', models.ManyToManyField(blank=True, related_name='SentLikes', to='groupApp.InterestGroup')),
            ],
        ),
        migrations.AddField(
            model_name='groupup',
            name='group1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group1', to='groupApp.interestgroup'),
        ),
        migrations.AddField(
            model_name='groupup',
            name='group2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group2', to='groupApp.interestgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupup',
            unique_together={('group1', 'group2')},
        ),
    ]
