# Generated by Django 4.0.2 on 2022-03-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupUpAccept', models.BooleanField(default=False)),
                ('is_super_groupup', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='interestgroup',
            name='matches',
        ),
        migrations.DeleteModel(
            name='GroupMatch',
        ),
        migrations.AddField(
            model_name='groupup',
            name='group1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group1', to='groupApp.interestgroup'),
        ),
        migrations.AddField(
            model_name='groupup',
            name='group2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group2', to='groupApp.interestgroup'),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='groupups',
            field=models.ManyToManyField(blank=True, to='groupApp.GroupUp'),
        ),
    ]
