# Generated by Django 4.0.2 on 2022-02-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groupApp", "0002_groupmatch_group2accept_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interestgroup",
            name="groupAdmin",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
