# Generated by Django 4.0.2 on 2022-03-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupApp', '0002_groupup_remove_interestgroup_matches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupup',
            old_name='is_super_groupup',
            new_name='isSuperGroupup',
        ),
    ]
