# Generated by Django 4.0.2 on 2022-03-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupApp', '0003_rename_is_super_groupup_groupup_issupergroupup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestgroup',
            old_name='date',
            new_name='meetingDate',
        ),
    ]
