# Generated by Django 4.0.2 on 2022-02-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupApp', '0003_alter_interestgroup_groupadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestgroup',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='meetingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='quote',
            field=models.CharField(default='', max_length=150),
        ),
    ]
