# Generated by Django 4.0.2 on 2022-03-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupApp', '0004_rename_date_interestgroup_meetingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgroup',
            name='meetingDate',
            field=models.DateField(blank=True, null=True, verbose_name='MeetingDate'),
        ),
        migrations.AlterUniqueTogether(
            name='groupup',
            unique_together={('group1', 'group2')},
        ),
    ]
