# Generated by Django 4.0.2 on 2022-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupApp', '0004_interestgroup_location_interestgroup_meetingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestgroup',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='wantToDoNext',
            field=models.TextField(default='', max_length=500),
        ),
    ]
